name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        run: |
          docker-compose up -d --build
      - name: try unit tests on elixir
        run: |
          docker-compose exec backend mix deps.get
          docker-compose exec backend mix test
      - name: destroy the created build
        run: |
          docker-compose down
