name: Docker CI

on:
  push:
    branches:
      - main

jobs:

  # ci:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v2

  #     - name: Build and push Docker image
  #       run: |
  #         docker-compose up -d --build
  #     - name: try unit tests on elixir
  #       run: |
  #         docker-compose exec -T backend mix deps.get
  #         docker-compose exec -T backend mix test
  #     - name: destroy the created build
  #       run: |
  #         docker-compose down
  cd:
    # needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Google Cloud VM
        run: |
          # SSH into your Google Cloud VM
          
          mkdir ~/.ssh
          touch ~/.ssh/id_rsa.pub
          echo "${{ secrets.SECRET_PUB_SSH_KEY}}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa.pub
          touch ~/.ssh/id_rsa
          echo "${{ secrets.SECRET_SSH_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no virtualmachine@34.155.108.18
          
          sudo su | \
          echo "${{ secrets.SECRET_USER_SSH_PUB_KEY}}" > ~/.ssh/id_rsa.pub | \
          chmod 600 ~/.ssh/id_rsa.pub | \
          echo "${{ secrets.SECRET_USER_SSH_KEY}}" > ~/.ssh/id_rsa | \
          chmod 600 ~/.ssh/id_rsa | \
          git clone git@github.com:redhabouzidi/Time_Manager.git | \ 
          cd Time_Manager | \ 
          git pull origin main | \
          docker compose build | \
          docker-compose up -d 
