name: Docker CI

on:
  push:
    branches:
      - main

jobs:

  # ci:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v2

  #     - name: Build and push Docker image
  #       run: |
  #         docker-compose up -d --build
  #     - name: try unit tests on elixir
  #       run: |
  #         docker-compose exec -T backend mix deps.get
  #         docker-compose exec -T backend mix test
  #     - name: destroy the created build
  #       run: |
  #         docker-compose down
  cd:
    # needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Creating ssh items
        run: |
          # SSH into your Google Cloud VM
          
          mkdir ~/.ssh
          touch ~/.ssh/id_rsa.pub
          echo "${{ secrets.SECRET_PUB_SSH_KEY}}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa.pub
          touch ~/.ssh/id_rsa
          echo "${{ secrets.SECRET_SSH_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa'
      - name: pulling the code
        run: |
          ssh -o StrictHostKeyChecking=no reda@34.155.108.18 'cd Time_Manager
          git pull origin main'
      - name: launching the app
        run: |
          ssh -o StrictHostKeyChecking=no reda@34.155.108.18 'docker-compose up -d --build -f ~/Time_Manager/docker-compose.yml up'
        
