name: Docker CI

on:
  push:
    branches:
      - main

jobs:

  # ci:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v2

  #     - name: Build and push Docker image
  #       run: |
  #         docker-compose up -d --build
  #     - name: try unit tests on elixir
  #       run: |
  #         docker-compose exec backend mix deps.get
  #         docker-compose exec backend mix test
  #     - name: destroy the created build
  #       run: |
  #         docker-compose down
  cd:
    # needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Google Cloud VM
        run: |
          # SSH into your Google Cloud VM
          mkdir ~/.ssh
          echo "${{ secrets.SECRET_SSH_KEY}}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa.pub
          ssh -i ~/.ssh/id_rsa.pub virtualmachine@34.155.108.18

          # Navigate to the project directory
          cd /virtual_machine

          # Initialize a Git repository (if it doesn't exist)
          if [ ! -d .git ]; then
            git init
          fi
          echo "hi"
          # Set up the remote repository to point to your GitHub repository
          git remote add origin https://github.com/redhabouzidi/Time_Manager

          # Fetch and pull the latest changes from the GitHub repository
          git pull origin main
          docker-compose up -d --build